### ISSUE TITLE
GDNative

### ISSUE THREAD

**Issue by rosshadden** [ggVGc/nim-godot#1]
I'm not sure if you still use Godot, or Nim for that matter, but if so have you considered getting Nim bindings to work using the recent GDNative support and the [godot_headers](https://github.com/GodotNativeTools/godot_headers) project?

**Comment by rawsp33d** [comment]
I was asking because I was going to make them myself, and was wondering if the effort was already being taken on by someone else.  I actually just noticed [godot-nim](https://github.com/pragmagic/godot-nim) after making this issue, so I'm closing this.
